# This is under development please do not edit this file

Normal_English_Font = "Noto Serif"
Normal_Bengali_Font = "Kalpurush"
Title_Heading_Font = "Siyam Rupali"
Mathematical_Symbol_Font = "DejaVu Math TeX Gyre"
Other_Symbols = "Opensymbol"
Math_Equation_Font = {
    "Variables": "DejaVu Math TeX Gyre",
    "Functions": "DejaVu Math TeX Gyre",
    "Numbers": "DejaVu Math TeX Gyre",
    "Text": "Kalpurush"
}

def main():
    if __name__ == "__main__":
            print("Everything is working well")

